
Citizen.CreateThread(function()
	AddTextEntry('CHALLENGER', 'Challenger Hellcat')
    AddTextEntry('DODGE', 'Dodge')
    AddTextEntry("WT_PIST", "Colt M1911")
    AddTextEntry("WT_PIST_CBT", "Glock 18")
    AddTextEntry("WT_PIST_GLOCK", "Glock 17")
    AddTextEntry("WT_PIST_50", "PMR 30")
    AddTextEntry("WT_PIST_LUGER", "Tokarev")
    AddTextEntry("WT_VPISTOL", "Five-seveN")
    AddTextEntry("WT_SNSPISTOL2", "Beretta 950")
    AddTextEntry("WT_PIST_DEAGLE", "Desert Eagle")
    AddTextEntry("W_ME_BAYONET", "BAYONET BOMBARDIAN")
    AddTextEntry("WT_AK47NEON", "AK-47 NEON")
end)